name: Twitch to YouTube Auto Upload

on:
    schedule:
        - cron: "0 0 * * *" # JST 9:00頃
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Run script
              env:
                  TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
                  TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
                  TWITCH_USER_ID: ${{ secrets.TWITCH_USER_ID }}
                  GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
                  YOUTUBE_TAGS: ${{ secrets.YOUTUBE_TAGS }}
                  PUBLISH_HOUR_JST: ${{ secrets.PUBLISH_HOUR_JST }}
                  PUBLISH_MINUTE_JST: ${{ secrets.PUBLISH_MINUTE_JST }}
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  LAST_DESCRIPTION_TEXT: ${{ secrets.LAST_DESCRIPTION_TEXT }}
                  PLAY_LIST_ID: ${{ secrets.PLAY_LIST_ID }}
                  NEXT_JA_PATTERN: ${{ secrets.NEXT_JA_PATTERN }}
                  NEXT_EN_PATTERN: ${{ secrets.NEXT_EN_PATTERN }}
              run: python main.py
